dist: trusty
sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
# whitelist
branches:
  only:
    - master
    - es6
node_js:
  - 6
before_install:
  - npm i -g grunt-cli
  - npm i -g npm@^3.0.0
  - npm i -g rollup
before_script:
  - npm prune
